name: CI Action

on:
  push:
      branches: 
        - '**'
        - '!master'
  pull_request:
      branches:
        - '**'
jobs:
  build:
      name: Build Job
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
          include:
            - os: macos-latest
              SHELL: bash
              SEP: /
              LS_CMD: ls -la
            - os: ubuntu-latest
              SHELL: bash
              SEP: /
              LS_CMD: ls -la
            - os: windows-latest
              SHELL: cmd
              SEP: \
              LS_CMD: dir /a
      defaults:
        run:
          shell: ${{ matrix.SHELL }}
      env:
        BUILD_DIR: ${{ github.workspace }}${{ matrix.SEP }}build
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: List Workspace
          run:  ${{matrix.LS_CMD}} ${{ github.workspace }}
        - name: Compile
          run: |
            echo "== CMAKE VERSION =="
            cmake --version
            echo "== CMAKE CONFIGURE =="
            cmake -B${{env.BUILD_DIR}} -DCI_TRIGGERED=1
            echo "== CMAKE BUILD =="
            cmake --build ${{env.BUILD_DIR}} --config Release
        - name: List Build
          run:  ${{matrix.LS_CMD}} ${{env.BUILD_DIR}}
        - name: Test
          run: |
            cd ${{env.BUILD_DIR}}
            ctest -C Release -T test --output-on-failure
            cd ${{ github.workspace }}
            